layout_spectrum: 0.6775113
typography_spectrum: 0.748105
color:
  saturation: 0.2899515
  lightness: 0.9527392
  brandStrength: 0.3983313
  rhythmicContrast: 0.8295416
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: OneWorldTradeCenterAdCollection
